# Решения по NumPy (Тема #3)

Формат разделов:

Задание N

Решение


In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)



## Задание 1
1. Задать массив $X$ несколькими способами.

$$X=\left[-15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15\right].$$

2. Найти количество элементов в $X$, обозначить $n$.

3. Создать «дубликат» массива $X$, обозначим его как $\tilde X$. Не изменяя $X$ изменить в $\tilde X$ элемент, равный $0$, на $1$.

4. Задать последовательность $Y$ для $i$ от $a$ до $b$ (с шагом $h$), где элементы определяются формулой:
$$Y_i=\frac{1}{i},\quad i\in\left\{a, a+h, a+2h, \ldots, b\right\},\quad i\neq 0.$$

5. Сгенерировать вложенную последовательность из $X=\{x_1, x_2, \ldots, x_n\}$ (пункт 1) и $Y=\{y_1, y_2, \ldots, y_n\}$ (пункт 4, взять $a=-15$, $b=15$):
$$Z=\left\{(x_1,y_1),(x_2,y_2),\ldots,(x_n,y_n)\right\}.$$

### Решение


In [ ]:
X1 = np.arange(-15, 16)
X2 = np.linspace(-15, 15, 31, dtype=int)
X3 = np.array(list(range(-15, 16)))

n = X1.size

X_tilde = X1.copy()
X_tilde[X_tilde == 0] = 1

a, b, h = -15, 15, 1
Y_idx = np.arange(a, b + h, h)
Y = np.zeros_like(Y_idx, dtype=float)
mask = Y_idx != 0
Y[mask] = 1.0 / Y_idx[mask]
Y[~mask] = np.nan

Z = np.column_stack((X1, Y))

X1, n, X_tilde, Y[:10], Z[:5]


(array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
         -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
         11,  12,  13,  14,  15]),
 31,
 array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
         -2,  -1,   1,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
         11,  12,  13,  14,  15]),
 array([-0.066667, -0.071429, -0.076923, -0.083333, -0.090909, -0.1     ,
        -0.111111, -0.125   , -0.142857, -0.166667]),
 array([[-15.      ,  -0.066667],
        [-14.      ,  -0.071429],
        [-13.      ,  -0.076923],
        [-12.      ,  -0.083333],
        [-11.      ,  -0.090909]]))

## Задание 2
В одномерном массиве, состоящем из $n$ вещественных элементов, вычислить:
- сумму положительных элементов массива;
- произведение элементов массива, расположенных между максимальным по модулю и минимальным по модулю элементами;
- сумму элементов массива с нечетными номерами;
- сумму элементов массива, расположенных между первым и последним отрицательными элементами;
- упорядочить элементы массива по возрастанию;
- упорядочить элементы массива по убыванию;
- сжать массив, удалив из него все элементы, модуль которых не превышает 1.

Входные данные смоделировать самостоятельно.

### Решение


In [ ]:
rng = np.random.default_rng(42)
arr = rng.normal(loc=0.0, scale=2.0, size=20)

sum_pos = arr[arr > 0].sum()

abs_idx_min = np.argmin(np.abs(arr))
abs_idx_max = np.argmax(np.abs(arr))
lo, hi = sorted((abs_idx_min, abs_idx_max))
prod_between = np.prod(arr[lo+1:hi]) if hi - lo > 1 else 1.0

sum_odd_idx = arr[1::2].sum()

neg_indices = np.where(arr < 0)[0]
if neg_indices.size >= 2:
    i1, i2 = neg_indices[0], neg_indices[-1]
    sum_between_negs = arr[i1+1:i2].sum()
else:
    sum_between_negs = 0.0

sorted_asc = np.sort(arr)
sorted_desc = np.sort(arr)[::-1]

compressed = arr[np.abs(arr) > 1]

sum_pos, prod_between, sum_odd_idx, sum_between_negs, sorted_asc[:5], sorted_desc[:5], compressed[:10]


(np.float64(13.377491275164463),
 np.float64(0.42116215218939435),
 np.float64(-5.067906497860542),
 np.float64(0.2531022423559135),
 array([-3.90207 , -2.604359, -2.079968, -1.917765, -1.718585]),
 array([2.254482, 1.881129, 1.758796, 1.756901, 1.555584]),
 array([-2.079968,  1.500902,  1.881129, -3.90207 , -2.604359, -1.706088,
         1.758796,  1.555584,  2.254482, -1.718585]))

## Задание 3
Для заданной матрицы размером 8 на 8 найти такие $k$, что $k$-я строка матрицы совпадает с $k$-м столбцом.

Найти сумму элементов в тех строках, которые содержат хотя бы один отрицательный элемент.

### Решение


In [4]:
rng = np.random.default_rng(0)
M = rng.integers(-3, 4, size=(8, 8))

k_matches = [k for k in range(M.shape[0]) if np.array_equal(M[k, :], M[:, k])]

row_has_neg = (M < 0).any(axis=1)
sum_rows_with_neg = M[row_has_neg].sum(axis=1)

M, k_matches, sum_rows_with_neg


(array([[ 2,  1,  0, -2, -1, -3, -3, -3],
        [-2,  2,  1,  3,  0,  1,  3,  2],
        [ 1,  0,  0,  3, -2,  2,  1, -3],
        [-1,  3,  0, -3,  2,  2,  2, -2],
        [-3,  3, -3,  0, -3, -1,  0, -1],
        [-1, -3, -3, -3, -3,  1,  0,  1],
        [-2,  1,  2, -1,  0,  3,  2,  3],
        [-1,  1,  3,  1,  2,  1,  1, -1]]),
 [],
 array([ -9,  10,   2,   3,  -8, -11,   8,   7]))

## Задание 4
Преобразовать вектор целых чисел в матричное двоичное представление.

Например, вектору $(0, 1, 2, 3, 4, 5, 6, 7)$ будет соответствовать матрица
$$
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 1 \\
0 & 1 & 0 \\
0 & 1 & 1 \\
1 & 0 & 0 \\
1 & 0 & 1 \\
1 & 1 & 0 \\
1 & 1 & 1
\end{pmatrix}.
$$

### Решение


In [ ]:
def to_binary_matrix(vec: np.ndarray, bits: int | None = None) -> np.ndarray:
    vec = np.asarray(vec, dtype=int)
    if bits is None:
        max_val = vec.max(initial=0)
        bits = max(1, int(np.ceil(np.log2(max_val + 1))))
    powers = 2 ** np.arange(bits - 1, -1, -1, dtype=int)
    return ((vec[:, None] // powers) % 2).astype(int)

v = np.arange(8)
bin_mat = to_binary_matrix(v)
v, bin_mat


(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]]))

## Задание 5
Рассмотрим два массива $A$ и $B$ формы $(8, 3)$ и $(2, 2)$. Необходимо найти строки $A$, которые содержат элементы каждой строки $B$ независимо от порядка элементов в $B$. Например, если
$$
A = \begin{pmatrix}
0 & 0 & 3 \\
1 & 1 & 2 \\
4 & 3 & 1 \\
3 & 1 & 1 \\
1 & 3 & 1 \\
2 & 0 & 3 \\
2 & 0 & 1 \\
0 & 0 & 3
\end{pmatrix},\quad
B = \begin{pmatrix}
0 & 3 \\
0 & 2 \\
\end{pmatrix},
$$
результат будет $\left(0, 5, 6, 7\right)$.

### Решение


In [ ]:
A = np.array([
    [0, 0, 3],
    [1, 1, 2],
    [4, 3, 1],
    [3, 1, 1],
    [1, 3, 1],
    [2, 0, 3],
    [2, 0, 1],
    [0, 0, 3],
])
B = np.array([
    [0, 3],
    [0, 2],
])

from collections import Counter

indices = []
for i, row in enumerate(A):
    countsA = Counter(row)
    ok = True
    for rowB in B:
        cntB = Counter(rowB)
        if any(countsA[val] < need for val, need in cntB.items()):
            ok = False
            break
    if ok:
        indices.append(i)

indices


[5]